### ISSUE TITLE
Hardcoded paths in parallel.jl

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/Juleana.jl#1]
Currently hardcoded to be used on MPP servers; should be replaced with more elegant solution using PropDicts package.

https://github.com/legend-exp/legend-julia-dsp-scripts/blob/bab3121b641e1ea70d2c04cc5d4a7a1ea2309c28/dsp/parallel.jl#L8-L29

**Comment by theHenks** [comment]
I think this can also be closed, seems like from the old days....Sorry!
