### ISSUE TITLE
Implement charge-trapping (CT) correction as done by MAJORANA (MJD) Collaboration

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/Juleana.jl#18]

**Comment by dcschaper** [comment]
Paper on MJD method can be found on the arXiv here: [Charge Trapping and Energy Performance of the MAJORANA Demonstrator](https://arxiv.org/pdf/2208.03424.pdf). This issue references the method described in Sections II through VI of this paper.

**Comment by theHenks** [comment]
I think this is not urgent now. We can do this later, for now the standard CT is enough.
