### ISSUE TITLE
Determine if there are differences between different detector types and how they are handled in the analysis processing chain

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/Juleana.jl#28]
For example: 'Are XXX corrections not performed on BEGe detectors? Do they not do YYY corrections on PPCs?' These could be CT corrections, DCR corrections, etc. Need to find out for sure if different detectors are handled or processed differently.

**Comment by theHenks** [comment]
We should in the same manner compare everything with pygama what concerns the processing.

**Comment by dcschaper** [comment]
@erin717 would actually have some excellent input on this topic. I will tag her here and also start a conversation with her.

**Comment by erin717** [comment]
At the moment, the only differences I know of are related to A/E and the COAX detectors. We do not calculate A/E at all for the coax detectors. All other detector geometries are handled the same in the processing.

That being said, this probably will not remain the case as the analysis matures. It's likely our PSD routines will need to be fine tuned for each detector geometry (I know for a fact that will likely be the case for the LQ cut).
