### ISSUE TITLE
Fix tailstats() implementation for decay time fits--eventually in JuliaPhysics/RadiationDetectorDSP.jl package?

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/Juleana.jl#31]
Until the decay-tail fitting functionality that is currently implemented in Florian's tailstats() function is added to the JuliaPhysics/RadiationDetectorDSP.jl package, fitting the decay time of the waveforms still needs to be done 'manually' within this analysis. At present I am using Florian's fork of RadiationDetectorDSP just to ensure we are processing data with the same code to avoid additional sources of confusion when comparing results. Putting this as an issue here so that this is at least known to any new users.

**Comment by theHenks** [comment]
Will be moved to LegendDSP.jl
