### ISSUE TITLE
cutLoader() in loader.jl currently only looks for file called 'cuts.h5.' Reformat this so that the filename is an input argument.

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/Juleana.jl#36]
https://github.com/legend-exp/legend-julia-dsp-scripts/blob/d6329033b982b793c85e4f9ac140692e07cebce8/utils/loader.jl#L6

Reformat this so that the filename is an input argument, but perhaps so that it defaults to 'cuts.h5' if a file name is not specified.

**Comment by theHenks** [comment]
Should be done with new layout
