### ISSUE TITLE
Naming Scheme for data production

### ISSUE THREAD

**Issue by theHenks** [legend-exp/Juleana.jl#63]
Incoporate new naming scheme for data productions as:
- Name: `jl-v0.1.0`
- First `jl` 
- First number data set, e.g. 1 --> `neutrino2024`
- Second number `production` version
- Third number for small debug changes

**Comment by theHenks** [comment]
We should also create a `Confluence` page for that to describe the naming and link to the paths.

**Comment by LisaSchlueter** [comment]
Confluence page: https://legend-exp.atlassian.net/wiki/spaces/LEGEND/pages/1358856301/JuLeAna+Working+Group#Processing-versions

I moved all the old versions into a `old_verions` folder and created soft links following the new naming convention. 
I didn't touch `current`, unsure how we want to handle this in the future. @theHenks  current could be a soft link to the most recent production for the future?

**Comment by LisaSchlueter** [comment]
PR: https://github.com/legend-exp/legend-julia-dataflow/pull/67

**Comment by theHenks** [comment]
I will close this since it should be done with the PR. Thanks @LisaSchlueter
